### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by kana800** [dhaladitya108/Python-File-Arranger#2]
Great Stuff 👍🏽  
Are you planning to add Linux support to this project? 
If so I can help @dhaladitya108  😄

**Comment by dhaladitya108** [comment]
Sure, it would be great

**Comment by kana800** [comment]
I will work on it tomorrow 😅

**Comment by kana800** [comment]
@dhaladitya108  I don't need to make any changes because the code work perfectly fine 😄 , I think it would be great idea if you add parser like [**argparse**](https://docs.python.org/3/library/argparse.html#module-argparse) so that the user don't need to change `src` and `destination` all the time and user can input the details from the command line. Maybe add a `requirements.txt` listing the modules that are being used.

```python
# Following are the sample source and destination folder. Please specify path according to your system directory
src = "/home/someone/Videos/"  # source folder
des = "/home/someone/sorted_files/"  # destination folder
```

check more info in the pull request
Thanks!
